CodeKiO/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blogs/', include('blogs.urls')),
    path('account/', include('accounts.urls')),
    path('shop/', include('ecommerce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('my-account', views.AccountView.as_view(), name="my-account"),
    path('logout', LogoutView.as_view(next_page='/'), name='logout'),
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
  path('', views.list),
  path('<slug:slug>', views.post, name='post'),
]

home/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.viewIndex.as_view(), name="index"),
    path('about', views.viewAboutIndex.as_view()),
    path('load-more', views.loadMore, name="loadMore"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from blogs.models import Post
from django.views import View
from django.http import JsonResponse
from django.core import serializers

# Create your views here.
class viewIndex(View):
   
   def get(self,request ):
      Data = {'Posts': Post.objects.all().order_by('-date')[:2]}
      return render(request, 'pages/index.html',Data)
   

class viewAboutIndex(View):
   def get(self,request ):
      return render(request, 'pages/profile.html')

def loadMore(request):
      if request.method == 'POST' and request.POST['total_item']:
         offset = int(request.POST['total_item'])
         limit = 2
         totalData = Post.objects.count()
         post_object = Post.objects.all().order_by('-date')[offset:limit+offset]
         post_json = serializers.serialize('json', post_object)
         return JsonResponse(data={
             'posts': post_json,
             'totalResults': totalData
         })

home/templates/pages/footer.html
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="footer-heading-title">Code Kìó</h2>
                <p>CodeKiO , hello world !</p>
            </div>
        </div>
    </div>
</footer>

home/templates/pages/header.html
{% load static %}
<header id="site-header">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
            <div class="site__header--logo">
                <a class="site__header--logo-main navbar-brand" href="/">
                    <img src="{% static 'assets/images/HC.png' %}" alt="CodeKìÓ" />
                    <h2 class="site__name">CodeKìó</h2>
                </a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blogs">Tutorial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about">About</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            <i class="fa-solid fa-user"></i>
                        </a>
                        <ul class="dropdown-menu">
                            {% if request.user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'account:my-account' %}">My account</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                             {% else %} 
                                <li><a class="dropdown-item" href="{% url 'account:index' %}?action=login">Login</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:index' %}?action=register">Register</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

home/templates/pages/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}CodeKìÓ{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Our project just needs Font Awesome Free's Solid and Brand files -->
        <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}" type="text/css">
        <link rel="stylesheet" href="{% static "assets/css/base.css" %}" type="text/css">
        <link rel="stylesheet" href="{% static "assets/css/home-list-post.css" %}" type="text/css">
        {% block style %}{% endblock %}
        <script src="{% static 'assets/js/jquery-3.6.3.min.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>

    </head>
    <body {% block class__body %}class="index"{% endblock %}">
        {% include './header.html' %}
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <main>
        {% block content %}
            {% include './banner.html' %} 
            {% include './shortcode-list-post.html' %}
        {% endblock %}
        </main>
        {% include './footer.html' %}
        {% include './loader.html' %}
        {% block javascript %}
            <script src="{% static 'assets/js/base.js' %}"></script>
        {% endblock %}
    </body>
</html>

home/templates/pages/item-post.html
<div class="col-12 col-md-6 col-lg-4 home__post--item">
    <div class="home__post--item-box">
        <a class="home__thumbnail__link" {% if slug %}href="{% url 'blogs:post' slug %}{% endif %}">
            <div class="home__post--item-thumbnail">
                {% if img %}
                <img src="{{ MEDIA_URL }}{{ img.url }}" />
                {% endif %}
            </div>
        </a>
        <div class="home__post--item__text">
            <h3 class="home__post--item__title"><a {% if slug %}href="{% url 'blogs:post' slug %}"{% endif %}>{{ title }}</a>
            </h3>
            <div class="home__post--item__excerpt">
                {% if content %}
                {{ content|striptags|truncatechars:200 }}
                {% endif %}
            </div>
        </div>
    </div>
</div>

home/templates/pages/loader.html
<div class="site__loader">
    <div class="loader">
        <div class="box box0">
            <div></div>
        </div>
        <div class="box box1">
            <div></div>
        </div>
        <div class="box box2">
            <div></div>
        </div>
        <div class="box box3">
            <div></div>
        </div>
        <div class="box box4">
            <div></div>
        </div>
        <div class="box box5">
            <div></div>
        </div>
        <div class="box box6">
            <div></div>
        </div>
        <div class="box box7">
            <div></div>
        </div>
        <div class="ground">
            <div></div>
        </div>
    </div>
</div>

home/templates/pages/profile.html
{% extends "pages/index.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static "assets/css/profile-user.css" %}" type="text/css">
{% endblock %}
{% block content %}
<div class="profile__main">
    <div class="profile__box">
        <div class="profile__main--container">
            <div class="gradient">
                <div class="content">
                    <h2>ChungKio</h2>
                    <p>28 years,Phu Tho,VN</p>
                    <br>
                    <p class="details">I am a developer working in Phu Tho.<br />User Interface Designer and front-end
                        developer</p>
                    <div class="icons">
                        <a href=""><i class="fa-brands fa-facebook"></i></i></a>
                        <a href=""><i class="fa-brands fa-twitter"></i></a>
                        <a href=""><i class="fa-brands fa-instagram"></i></a>
                        <a href=""><i class="fa-brands fa-github-alt"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/pages/shortcode-list-post.html
{% if Posts %}
<section class="container home__list--post">
    <div class="row home__post--box-heading">
        <div class="col-12 col-md-12 col-lg-12 section__post--heading">
            <h2 class="section-heading-title">What's new in codekìó</h2>
            <p class="section-heading-content">Read the latest tutorials</p>
        </div>
    </div>
    <div class="row home__post--box">
        {% for post in Posts %}
            {% include './item-post.html' with slug=post.slug img=post.images title=post.title content=post.body %}
        {% endfor %}

    </div>
    <div class="row row-home__post--load-item">
        <div class="col-12 home__post--load-item">
            <button class="btn-load button__loadMore"><span>Load More</span></button>
        </div>
        {% csrf_token %}
    </div>
</section>
<script>
    $(document).ready(function () {
        $('.button__loadMore').click(function () {
            var _currentPost = $('.home__post--item').length;
            console.log('Number: ',_currentPost);
            if (_currentPost > 0) {
                $.ajax({    
                    url: '{% url 'homepage:loadMore' %}',
                    type: 'POST',
                    data: {
                        'total_item': _currentPost,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    dataType: 'json',
                    beforeSend: function(){
                        $('.site__loader').addClass('active');
                    },
                    success: function (data) {
                        var _html = '';
                        var _dataJson = $.parseJSON(data.posts);
                        if(_dataJson){
                            $.each(_dataJson, function (index, item) {
                                var _content = item.fields.body
                                var _contentResult = $(_content).text().substr(0, 200)+'...';
                                {% comment %} _html += `{% include './item-post.html' with slug=item.fields.slug  img=item.fields.images  title=item.fields.title content=item.fields.body %}
                                ` {% endcomment %}
                                _html += `
                                <div class="col-12 col-md-6 col-lg-4 home__post--item">
                                    <div class="home__post--item-box">
                                        <a class="home__thumbnail__link" href="/blogs/${ item.fields.slug }">
                                            <div class="home__post--item-thumbnail">
                                                <img src="/media/${ item.fields.images }" />
                                            </div>
                                        </a>
                                        <div class="home__post--item__text">
                                            <h3 class="home__post--item__title"><a href="/blogs/${ item.fields.slug }">${ item.fields.title }</a>
                                            </h3>
                                            <div class="home__post--item__excerpt">
                                                ${ _contentResult }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                `
                            });
                            $('.home__post--box').append(_html);
                            var _countItems = $('.home__post--item').length;
                            if(_dataJson.totalResults = _countItems){
                                $('.row-home__post--load-item').remove()
                            }
                            $('.site__loader').removeClass('active');
                        }
                       
                    },
                    error: function (err) {
                        console.log('Err: ',err);
                    }
                });
            }else{
                $('.row-home__post--load-item').remove();
            }
        });
    });
</script>
{% endif %}